"""Register the demo agents once and write per-example .env files.

Idempotent: if `examples/<name>/.env` already has GOA_API_KEY +
GOA_PARTICIPANT_ID, that agent is skipped. Re-run after `make demo-clean`
(which wipes goa.db AND the per-example .env files) to get a fresh set.

Requires `make goa` running in another terminal — this script does not
boot a hub of its own.
"""

from __future__ import annotations

import asyncio
import os
import sys
from dataclasses import dataclass
from pathlib import Path

import httpx

REPO_ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_DIR = REPO_ROOT / "examples"

from goa_sdk import Goa  # noqa: E402


@dataclass(frozen=True)
class AgentSpec:
    dir_name: str
    type: str
    name: str
    description: str
    capabilities: list[str]


AGENTS: list[AgentSpec] = [
    AgentSpec(
        dir_name="payments-agent",
        type="agent",
        name="payments-agent",
        description="processes refund and billing inquiries",
        capabilities=["payments", "refunds"],
    ),
    AgentSpec(
        dir_name="support-agent",
        type="agent",
        name="support-agent",
        description="customer support; consults payments on refunds",
        capabilities=["support"],
    ),
    AgentSpec(
        dir_name="chat-service",
        type="service",
        name="chat-service",
        description="fronts a chat UI for the customer",
        capabilities=["chat"],
    ),
]


def _existing_creds(env_path: Path) -> tuple[str, str] | None:
    if not env_path.exists():
        return None
    api_key = participant_id = None
    for raw in env_path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        value = value.strip().strip('"').strip("'")
        if key.strip() == "GOA_API_KEY":
            api_key = value
        elif key.strip() == "GOA_PARTICIPANT_ID":
            participant_id = value
    if api_key and participant_id:
        return api_key, participant_id
    return None


def _write_env(env_path: Path, agent: AgentSpec, api_key: str, participant_id: str) -> None:
    body = (
        "# Generated by scripts/register_agents.py — do not edit by hand.\n"
        "# Delete this file and re-run `make setup` to re-register.\n"
        f"GOA_API_KEY={api_key}\n"
        f"GOA_PARTICIPANT_ID={participant_id}\n"
    )
    env_path.write_text(body)


async def _check_hub(base_url: str) -> None:
    """Confirm the hub is reachable. Any HTTP response (including 401) means
    the server is up; only connection errors abort setup."""
    try:
        async with httpx.AsyncClient(timeout=5.0) as http:
            await http.get(f"{base_url}/participants")
    except httpx.HTTPError as exc:
        sys.stderr.write(
            f"hub not reachable at {base_url} ({exc}). "
            "Start it with `make goa` in another terminal, then re-run `make setup`.\n"
        )
        sys.exit(1)


async def _register(base_url: str, agent: AgentSpec) -> tuple[str, str]:
    client, api_key, participant = await Goa.register_participant(
        base_url,
        type=agent.type,
        name=agent.name,
        description=agent.description,
        capabilities=agent.capabilities,
    )
    try:
        return api_key, str(participant.id)
    finally:
        await client.aclose()


async def main() -> None:
    base_url = os.environ.get("GOA_BASE_URL", "http://127.0.0.1:8000")
    await _check_hub(base_url)

    any_registered = False
    for agent in AGENTS:
        env_path = EXAMPLES_DIR / agent.dir_name / ".env"
        existing = _existing_creds(env_path)
        if existing is not None:
            print(f"[{agent.name}] already registered ({existing[1]}); skipping")
            continue
        api_key, participant_id = await _register(base_url, agent)
        _write_env(env_path, agent, api_key, participant_id)
        print(f"[{agent.name}] registered {participant_id} → {env_path.relative_to(REPO_ROOT)}")
        any_registered = True

    if not any_registered:
        print("\nAll agents already registered. Delete the .env files or run "
              "`make demo-clean` to start fresh.")
    else:
        print("\nDone. Stop `make goa` and run `make demo`.")


if __name__ == "__main__":
    asyncio.run(main())
