#!/usr/bin/env bash
# 00_register.sh — bootstrap a chat-service identity with raw curl.
#
# Mirrors what `Goa.register_participant(...)` does in the Python SDK
# (cf. examples/chat-service/cli.py:33-39): one POST to /participants,
# capture the one-shot api_key from the response. Then look up the
# support agent's id via GET /participants?capability=support so the
# next script can target it.
#
# Writes credentials and IDs to .env.http for downstream scripts.

set -euo pipefail
cd "$(dirname "$0")"

BASE_URL="${BASE_URL:-http://127.0.0.1:8000}"

echo "→ POST $BASE_URL/participants"
register_response="$(
  curl -sS -X POST "$BASE_URL/participants" \
    -H "Content-Type: application/json" \
    -d '{
      "type": "service",
      "name": "chat-service-curl",
      "description": "curl-driven chat-service participant",
      "capabilities": ["chat"]
    }'
)"

CHAT_API_KEY="$(echo "$register_response" | jq -r '.api_key')"
CHAT_PARTICIPANT_ID="$(echo "$register_response" | jq -r '.participant.id')"
echo "  registered chat-service-curl as $CHAT_PARTICIPANT_ID"

echo "→ GET $BASE_URL/participants?capability=support"
support_response="$(
  curl -sS "$BASE_URL/participants?capability=support" \
    -H "Authorization: Bearer $CHAT_API_KEY"
)"
SUPPORT_ID="$(echo "$support_response" | jq -r '.participants[0].id // empty')"

if [ -z "$SUPPORT_ID" ]; then
  echo
  echo "error: no participant with capability=support is registered."
  echo "       run \`make demo\` from the repo root, wait for the three demo"
  echo "       agents to come up, then re-run this script."
  exit 1
fi
echo "  found support agent: $SUPPORT_ID"

cat > .env.http <<EOF
# Generated by examples/http/00_register.sh — gitignored.
BASE_URL=$BASE_URL
CHAT_API_KEY=$CHAT_API_KEY
CHAT_PARTICIPANT_ID=$CHAT_PARTICIPANT_ID
SUPPORT_ID=$SUPPORT_ID
EOF
echo "→ wrote .env.http"
